name: Node.js Package Publish

on:
  workflow_run:
    workflows: ['release'] # After the Release workflow finishes
    types:
      - completed

jobs:
  publish_and_sync:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      # 1. Checkout the main branch first to get the latest release state
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main # Explicitly check out the main branch

      # Set up node for npm-related tasks
      - name: Set up Node.js for npm publish
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      # Publish to npm
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
